version: '3.9'

services:
    database: 
        image: postgres
        container_name: db_carrentalx
        restart: always
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=carrentalx
        volumes:
            - pgdata:/data/postgres 
    app:
        build: .
        container_name: carrentalx
        ports:
            - 3333:3333
            - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database 


volumes:
    pgdata:
        driver: local